@startuml PISPOTPValidateModel

title PISPOTPValidateModel

[*] --> outboundServer: ""PATCH /consentRequests/{ID}/validate""
outboundServer --> start: creation of state machine
start --> requestAction
requestAction --> succeeded:\ncall ""PATCH /consentRequests/{ID}/""\nrecieved ""POST /CONSENTS""
requestAction --> errorFromCallback:\ncall ""PATCH /consentRequests/{ID}/""\nrecieved ""PUT /consentRequests/{ID}/error""
succeeded --> PISPStoreConsent:\ncall ""POST /consents/"" to Auth service

@enduml
