@startuml PISPOTPValidateModel

title PISPOTPValidateModel

[*] --> outboundServer: ""PATCH /consentRequests/{ID}/validate""
outboundServer --> start: on creation of state machine
start --> requestAction
requestAction --> succeeded:\ncall ""PATCH /consentRequests/{ID}/""\nwait for ""POST /CONSENTS"" or ""PUT /consentRequests/{ID}/error""

succeeded --> [*]

@enduml
