openapi: 3.0.1
info:
  title: Mojaloop Thirdparty Inbound Scheme Adapter
  description: >
    Specification for the Thirdparty Inbound Scheme Adapter API

    Please see other documentation on
    https://github.com/mojaloop/thirdparty-scheme-adapter for more information.


    **Note on terminology:** The term "Switch" is equal to the term "Hub", and
    the term "FSP" is equal to the term "DFSP".
  license:
    name: 'TBD'
    url: 'TBD'
  version: 0.1.0
paths:
  /accounts/{ID}:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/accounts_ID.yaml'
  /accounts/{ID}/error:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/accounts_ID_error.yaml'
  /authorizations:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/authorizations.yaml'
  /authorizations/{ID}:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/authorizations_ID.yaml'
  /consentRequests/{ID}:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/consentRequests_ID.yaml'
  /consentRequests/{ID}/error:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/consentRequests_ID_error.yaml'
  /consents:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/consents.yaml'
  /health:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/health.yaml'
  /metrics:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/metrics.yaml'
  /thirdpartyRequests/transactions:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/thirdpartyRequests_transactions.yaml'
  /thirdpartyRequests/transactions/{ID}/authorizations:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/thirdpartyRequests_transactions_ID_authz.yaml'
  /thirdpartyRequests/transactions/{ID}:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/thirdpartyRequests_transactions_ID.yaml'
  /thirdpartyRequests/transactions/{ID}/error:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/thirdpartyRequests_transactions_ID_error.yaml'
