openapi: 3.0.1
info:
  title: Mojaloop Thirdparty Outbound Scheme Adapter
  description: >
    Specification for the Thirdparty Outbound Scheme Adapter API

    Please see other documentation on
    https://github.com/mojaloop/thirdparty-scheme-adapter for more information.


    **Note on terminology:** The term "Switch" is equal to the term "Hub", and
    the term "FSP" is equal to the term "DFSP".
  license:
    name: 'TBD'
    url: 'TBD'
  version: 0.1.0
paths:
  /health:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/health.yaml'
  /metrics:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/metrics.yaml'
  /authorizations:
    $ref: paths/authorizations.yaml

  # pispTransaction.model
  /thirdpartyTransaction/partyLookup:
    $ref: paths/thirdpartyTransaction_partyLookup.yaml
  /thirdpartyTransaction/{ID}/initiate:
    $ref: paths/thirdpartyTransaction_ID_initiate.yaml
  /thirdpartyTransaction/{ID}/approve:
    $ref: paths/thirdpartyTransaction_ID_approve.yaml

  /thirdpartyRequests/transactions/{ID}/authorizations:
    $ref: paths/thirdpartyRequests_transactions_ID_authorizations.yaml

  /linking/providers:
    $ref:  paths/linking_providers.yaml
  /linking/accounts/{fspId}/{userId}:
    $ref: paths/linking_accounts.yaml
  /linking/request-consent:
    $ref: paths/linking_request_consent.yaml
  /linking/request-consent/{ID}/authenticate:
    $ref: paths/linking_request_consent_ID_authenticate.yaml
