# Note: I've manually edited the `responses` section to replace all errors with a single
# `default` entry, as suggested in https://swagger.io/docs/specification/describing-responses/
# This is because each of the error responses contains the same schema.
# Doing do makes the swagger doc much more readable, especially when rendered
openapi: 3.0.1
info:
  title: Mojaloop Thirdparty Outbound SDK
  description: >
    Specification for the Thirdparty Outbound SDK API.

    This API is a synchronous API which makes integrating with the Mojaloop 3rd Party API easier.

    Please see other documentation on
    https://github.com/mojaloop/thirdparty-sdk for more information.
  license:
    name: Apache 2.0
  version: 0.1.1
servers:
  - url: http://sandbox.mojaloop.io/switch-ttk-backend
    description: The mock 3p-scheme-adapter server running in the Mojaloop Sandbox
  - url: http://localhost:15000
    description: A locally running TTK instance
paths:
  /health:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/v1_0/openapi3/paths/health.yaml'
  /metrics:
    $ref: '../../../../node_modules/@mojaloop/api-snippets/thirdparty/v1_0/openapi3/paths/metrics.yaml'
  /thirdpartyTransaction/partyLookup:
    $ref: paths/thirdpartyTransaction_partyLookup.yaml
  /thirdpartyTransaction/{ID}/initiate:
    $ref: paths/thirdpartyTransaction_ID_initiate.yaml
  /thirdpartyTransaction/{ID}/approve:
    $ref: paths/thirdpartyTransaction_ID_approve.yaml
  /linking/providers:
    $ref:  paths/linking_providers.yaml
  /linking/accounts/{fspId}/{userId}:
    $ref: paths/linking_accounts.yaml
  /linking/request-consent:
    $ref: paths/linking_request_consent.yaml
  /linking/request-consent/{ID}/authenticate:
    $ref: paths/linking_request_consent_ID_authenticate.yaml
  /linking/request-consent/{ID}/pass-credential:
    $ref: paths/linking_request_consent_ID_pass_credential.yaml
